version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - echo Build Starting on `date`
      - cd server2
      - chmod 700 ./gradlew
      - ./gradlew build
  post_build:
    commands:
      - echo $(basename ./server2/build/libs/server-0.0.1-SNAPSHOT.jar)
artifacts:
  files:
    - server2/build/libs/server-0.0.1-SNAPSHOT.jar
    - server2/scripts/**
    - server2/appspec.yml
  discard-paths: yes

cache:
  paths:
    - '/root/.gradle/caches/**/*'